version: "3.8"

services:
  collector:
    image: cloudreactor/aws-otel-collector-cloudreactor
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4317:4317" # OTLP receiver
      - "13133:13133"     # Health check
    environment:
      AWS_REGION: us-west-2
      PROC_WRAPPER_LOG_LEVEL: DEBUG

  # Check your Dockerfile against best-practices:
  # See https://github.com/hadolint/hadolint
  hadolint:
    image: hadolint/hadolint
    volumes:
      - ./Dockerfile:/mnt/Dockerfile
    entrypoint: "/bin/hadolint /mnt/Dockerfile"
    profiles: ["dev"]